### ISSUE TITLE
Allow multiple internal_objects declaration as list or dict

### ISSUE THREAD

**Issue by rcattin** [THipster/THipster#101]
### Feature Spec

Currently I have to create 1block/internal object :

```
region: europe-west1
cors:
    maxAge: 10
    source: dnkzfnazklfnza
cors:
    maxAge: 20
    source: azuifdzauigdb
```

I want to be able to declare multiple internal objects from one block in a list:
```
region: europe-west1
cors:
    - maxAge: 10
      name : europe
      source: dnkzfnazklfnza
    - maxAge: 20
      source: azuifdzauigdb
```

### Implementation Notes

- [ ] Update DSL to allow lists of dictionnaries
- [x] In internal_object creation : Match value type (list/ dict) to do the right thing

### Component

Engine
